' Here is comment
/' Here is block comment '/
' preview : ALT + D


@startuml Sequence Diagram
participant Alice
participant Bob
participant Red
== Initialization ==
== Repetition ==
Alice -> Bob: Request
activate Bob
Bob -> Red: Request
activate Red
Red -> Red: Self
note right: Here is note
Red --> Bob: Response
deactivate Red
destroy Red
...5 minutes...
return Response
deactivate Bob
alt#Gold #LightBlue Successful case
    Bob -> Alice: Authentication Accepted
else #Pink Failure
    loop 1000 times
        Bob -> Alice: Error
    end
    Bob -> Alice: Authentication Rejected
end
|||
Bob ->x Alice
Bob -> Alice
Bob ->> Alice
Bob -\ Alice
Bob \\- Alice
Bob //-- Alice
|||
Bob ->o Alice
Bob o\\-- Alice
Bob <-> Alice
Bob <->o Alice
@enduml

@startuml Activity Diagram
title My title
start
:Hello world;
if (a==b) then (a)
    :process a;
elseif (a==c) then (b)
    :process b;
else (no)
    :process \nabc;
endif
:This is defined on 
several **lines**;
stop
'''''''''''''''''''''''''''''''
start
repeat :read data;
  :generate diagrams;
backward:more;
repeat while (data == null)
stop
''''''''''''''''''''''''''''''
start
switch (condition)
case ( condition A )
  :Text 1;
case ( condition B ) 
  :Text 2;
case ( condition C )
  :Text 3;
case ( condition D )
  :Text 4;
case ( condition E )
  :Text 5;
endswitch
stop

@enduml

@startuml Class Diagram
class A {
    + public
    - private
    # protected
    + public()
    - private()
    # protected()
    ~ A
}

class B
class C
class D
A ^-- B
B *-- C
B -l-> C
C o-- D
C <.. D: use


interface I
@enduml

